import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import '../styles/globals.css';
import styles from './layout.module.scss';
import Header from './modules/layout/header/header';

import { ClientThemeProvider } from '../providers';
import AppQueryProvider from '../providers/query-client-provider';
import { StoreProvider } from '../providers/store-provider';
import Jumbotron from './modules/layout/jumbotron/jumbotron';
import { FooterContainer } from './modules/layout/footer/footer-container';

export const metadata: Metadata = {
  title: 'Optimized Closets',
  description: 'Generated by create next app',
};
const lato = Lato({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <AppQueryProvider>
          <ClientThemeProvider>
            <StoreProvider>
              <header>
                <Header />
              </header>
              <section>
                <Jumbotron />
              </section>
              <main className={styles.main_content}>{children}</main>
              {/* <section className={styles.subscribe_wrapper}>
                <Subscribe />
              </section> */}
              <footer>
                <FooterContainer />
              </footer>
            </StoreProvider>
          </ClientThemeProvider>
        </AppQueryProvider>
      </body>
    </html>
  );
}
