import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import '../styles/globals.css';
import styles from './layout.module.scss';
import Header from './layout/header/header';

import { PrimaryButton } from '@packages/atoms';
import { ClientThemeProvider } from '../providers';
import AppQueryProvider from '../providers/query-client-provider';
import { StoreProvider } from '../providers/store-provider';

export const metadata: Metadata = {
  title: 'Optimized Closets',
  description: 'Generated by create next app',
};
const lato = Lato({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <AppQueryProvider>
          <ClientThemeProvider>
            <StoreProvider>
              <header>
                <Header />
              </header>
              {/* <main>{children}</main> */}
              <section className={styles.subscribe_wrapper}>
                {/* <Subscribe /> */}
              </section>
              <footer>
                <PrimaryButton>Hello Mono Repo (Next)</PrimaryButton>
              </footer>
            </StoreProvider>
          </ClientThemeProvider>
        </AppQueryProvider>
      </body>
    </html>
  );
}
