import type { Metadata } from 'next';
import { WelcomeContainer } from './modules/welcome';
import { GalleryContainer } from './modules/gallery';
import { ApproachContainer } from './modules/approach';
import { ReviewContainer } from './modules/review';
export const metadata: Metadata = {
  title: 'Optimized Closets',
  description: 'Generated by create next app',
};
export default async function Page() {
  return (
    <>
      <WelcomeContainer />
      <GalleryContainer />
      <ApproachContainer />
      <ReviewContainer />
    </>
  );
}
