name: Deploy Monorepo App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Build the service app
        run: |
          cd apps/service
          yarn build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and dependencies
        run: |
          ssh -i ~/.ssh/id_799 -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }} 'bash -s' <<'EOF'
          sudo apt update
          sudo apt install -y nodejs npm
          git clone https://github.com/BabakKhajavi/optimized-home-mono-repo.git
          cd optimized-home-mono-repo
          yarn install
          cd apps/service
          yarn build
          pm2 restart all
          EOF

      - name: Create SSH private key file
        run: |
          echo "${{ secrets.DROPLET_SSH_KEY }}" > /tmp/droplet_key
          chmod 600 /tmp/droplet_key

      - name: Copy application files to droplet
        run: scp -i /tmp/droplet_key -r ./your-repo ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }}:/var/www/your-repo

      - name: Deploy application
        run:
          ssh -i /tmp/droplet_key -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }} '
          cd /var/www/optimized-home-mono-repo
          yarn install
          cd apps/service
          yarn build
          pm2 restart all'
