name: Deploy Monorepo App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build the service app
        run: |
          cd apps/service
          yarn build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH private key file
        run: |
          echo "${{ secrets.DROPLET_SSH_KEY }}" > /tmp/droplet_key
          chmod 600 /tmp/droplet_key

      - name: Copy application files to droplet
        run: scp -i /tmp/droplet_key -r ./optimized-home-mono-repo ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }}:/optimized-home-mono-repo

      - name: Install Node.js and dependencies on droplet
        run:
          ssh -i /tmp/droplet_key -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }} '
          cd /optimized-home-mono-repo
          sudo apt update
          sudo apt install -y nodejs npm
          yarn install
          cd apps/service
          yarn build
          pm2 start dist/server.js --name service-app
          pm2 save'
