# .github/workflows/deploy-service-app.yml
name: Deploy Service App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Build Docker image
        run: docker build -t service-app ./apps/service

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag and Push Docker image to Docker Hub
        run: |
          docker tag service-app:latest ${{ secrets.DOCKER_USERNAME }}/service-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/service-app:latest

      - name: Create SSH private key file
        run: |
          echo "${{ secrets.DROPLET_SSH_KEY }}" > /tmp/droplet_key
          sed -i 's/\\n/\n/g' /tmp/droplet_key
          chmod 600 /tmp/droplet_key

      - name: Deploy Docker image to DigitalOcean Droplet
        run:
          ssh -i /tmp/droplet_key -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }} '
          docker pull ${{ secrets.DOCKER_USERNAME }}/service-app:latest &&
          docker stop service-app || true &&
          docker rm service-app || true &&
          docker run -d --name service-app -p 3000:3000 \
          -e SERVICE_CORS_ORIGIN_PORTAL=${{ secrets.SERVICE_CORS_ORIGIN_PORTAL }} \
          -e SERVICE_CORS_ORIGIN_APP=${{ secrets.SERVICE_CORS_ORIGIN_APP }} \
          -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
          -e DB_HOST=localhost \
          -e DB_USERS=${{ secrets.DB_USERS }} \
          -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          -e DB_DATABASE=${{ secrets.DB_DATABASE }} \
          -e SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }} \
          -e SENDGRID_REQUEST_ALARM_TEMPLATE_ID=${{ secrets.SENDGRID_REQUEST_ALARM_TEMPLATE_ID }} \
          -e SENDGRID_REQUEST_AUTO_REPLY_TEMPLATE_ID=${{ secrets.SENDGRID_REQUEST_AUTO_REPLY_TEMPLATE_ID }} \
          -e PORT=${{ secrets.PORT }} \
          ${{ secrets.DOCKER_USERNAME }}/service-app:latest'
